# Name: Dishang Dalwadi
# Reg No.: 24-27-12
# M.Tech Data Science
# Assignment 2

# Q1.
a) Create a variable named var1 that stores an array of numbers from 0 to 30,
inclusive. Print var1 and its shape. Hint : arange

In [27]:
import numpy as np

# Create an array using np.arange from 0 to 30 inclusive
var1 = np.arange(0, 31)

# Print the array and its shape
print("Array:", var1)
print("Shape:", var1.shape)



Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape: (31,)


b) Change var2 to a validly-shaped two-dimensional matrix and store it in a
new variable called var2. Print var2 and its shape. Hint: Use the reshape function

In [28]:
# Create the original array var1
var1 = np.arange(0, 31)

# Reshape var1 into a two-dimensional matrix and store it in var2
var2 = var1.reshape(1, 31)  # Reshape into a matrix with 1 row and 31 columns

# Print the new matrix and its shape
print("2D Matrix (var2):\n", var2)
print("Shape:", var2.shape)



2D Matrix (var2):
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30]]
Shape: (1, 31)


c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
Print var3 and its shape.

In [29]:
# Create the original array var1
var1 = np.arange(0, 31)

# Reshape var1 into a three-dimensional matrix
var3 = var1.reshape(1, 31, 1)  # Example shape: (1, 31, 1)

# Print the new 3D matrix and its shape
print("3D Matrix (var3):\n", var3)
print("Shape:", var3.shape)


3D Matrix (var3):
 [[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]]]
Shape: (1, 31, 1)


d) Use two-dimensional array indexing to set the first value in the second row of var2
to -1. Now look at var1 and var3. Did they change? Explain what’s
going on. (Hint: does reshape return a view or a copy?)

In [30]:
# Create the original array var1
var1 = np.arange(0, 31)

# Remove the last element to make it 30 elements, as we want to reshape into (5, 6)
var1 = var1[:-1]

# Reshape var1 into a two-dimensional matrix (var2)
var2 = var1.reshape(5, 6)

# Modify the first value in the second row of var2
var2[1, 0] = -1

# Print var2, var1, and var3 (before and after)
print("Updated 2D Matrix (var2):\n", var2)
print("Original Array (var1):\n", var1)

# Reshape var1 into a three-dimensional matrix (var3)
var3 = var1.reshape(3, 5, 2)

print("3D Matrix (var3):\n", var3)


Updated 2D Matrix (var2):
 [[ 0  1  2  3  4  5]
 [-1  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Original Array (var1):
 [ 0  1  2  3  4  5 -1  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
3D Matrix (var3):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [-1  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


e) Another thing that comes up a lot with array shapes is thinking about how to
aggregate over specific dimensions. Figure out how the NumPy sum function
works (and the axis argument in particular) and do the following:
(i) Sum var3 over its second dimension and print the result.
(ii) Sum var3 over its third dimension and print the result.
(iii) Sum var3 over both its first and third dimensions and print the result.

In [31]:
# Create the original array var1 and modify it to 30 elements
var1 = np.arange(0, 31)[:-1]

# Reshape var1 into a 3D matrix var3
var3 = var1.reshape(3, 5, 2)  # Shape: (3, 5, 2)

# (i) Sum var3 over its second dimension (axis=1)
sum_over_second_dim = np.sum(var3, axis=1)
print("Sum over second dimension (axis=1):\n", sum_over_second_dim)
print("Shape:", sum_over_second_dim.shape)

# (ii) Sum var3 over its third dimension (axis=2)
sum_over_third_dim = np.sum(var3, axis=2)
print("Sum over third dimension (axis=2):\n", sum_over_third_dim)
print("Shape:", sum_over_third_dim.shape)

# (iii) Sum var3 over both its first and third dimensions (axis=(0, 2))
sum_over_first_third_dim = np.sum(var3, axis=(0, 2))
print("Sum over first and third dimensions (axis=(0, 2)):\n", sum_over_first_third_dim)
print("Shape:", sum_over_first_third_dim.shape)


Sum over second dimension (axis=1):
 [[ 20  25]
 [ 70  75]
 [120 125]]
Shape: (3, 2)
Sum over third dimension (axis=2):
 [[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]]
Shape: (3, 5)
Sum over first and third dimensions (axis=(0, 2)):
 [ 63  75  87  99 111]
Shape: (5,)


f) Write code to do the following:
(i) Slice out the second row of var2 and print it.
(ii) Slice out the last column of var2 using the -1 notation and print it.
(iii) Slice out the top right 2 × 2 submatrix of var2 and print it.

In [32]:
# Create the original array var1 and modify it to 30 elements
var1 = np.arange(0, 31)[:-1]

# Reshape var1 into a two-dimensional matrix (var2)
var2 = var1.reshape(5, 6)  # Shape: (5, 6)

# (i) Slice out the second row of var2
second_row = var2[1, :]  # Indexing to get the second row
print("Second Row of var2:\n", second_row)

# (ii) Slice out the last column of var2 using -1 notation
last_column = var2[:, -1]  # Indexing to get the last column
print("Last Column of var2:\n", last_column)

# (iii) Slice out the top right 2 × 2 submatrix of var2
top_right_submatrix = var2[0:2, -2:]  # Get the first two rows and last two columns
print("Top Right 2x2 Submatrix of var2:\n", top_right_submatrix)


Second Row of var2:
 [ 6  7  8  9 10 11]
Last Column of var2:
 [ 5 11 17 23 29]
Top Right 2x2 Submatrix of var2:
 [[ 4  5]
 [10 11]]


# Q2.
a) The most basic kind of broadcast is with a scalar, in which you can perform a
binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to
perform that operation with the scalar for every element of the array. To try this
out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

In [33]:
# Create a vector from 1 to 10 by adding 1 to the result of np.arange(10)
vector = np.arange(10) + 1

# Print the resulting vector
print("Vector from 1 to 10:\n", vector)


Vector from 1 to 10:
 [ 1  2  3  4  5  6  7  8  9 10]


b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this
using the vector you just created, and adding it to a reshaped version of itself.

In [34]:
# Create a vector from 1 to 10
vector = np.arange(10) + 1  # This gives us [1, 2, 3, ..., 10]

# Create a 10x10 matrix A where A[i, j] = i + j
A = vector[:, np.newaxis] + vector  # Reshape vector to a column vector and add

# Print the resulting matrix A
print("Matrix A (10x10) where A[i, j] = i + j:\n", A)


Matrix A (10x10) where A[i, j] = i + j:
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


c) A very common use of broadcasting is to standardize data, i.e., to make it have
zero mean and unit variance. First, create a fake “data set” with 50 examples,
each with five dimensions.
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )

In [36]:
# Create a fake dataset with 50 examples and 5 dimensions
data = np.exp(npr.randn(50, 5))

# Print the resulting dataset
print("Fake Dataset (50 examples, 5 dimensions):\n", data)


Fake Dataset (50 examples, 5 dimensions):
 [[ 3.19230065  0.38387428  0.38692018  1.27279691  0.10062715]
 [ 0.15479216  2.52139838  1.47551263  0.48465496  0.9351145 ]
 [ 2.74953378  0.69866239  0.29415409  2.03255244  7.23714842]
 [ 0.71798918  1.03104056  0.39352771  3.61051886  0.96596917]
 [ 0.62622725  0.96827861  1.68748112  0.16481619  0.33108947]
 [ 0.31505742  1.3622766   0.81328122  0.70979654  0.21945152]
 [ 0.617513    0.65917364  0.35431778  0.88780738  0.64382128]
 [ 0.17663348  1.12241003  1.74638361  0.4662626   0.53710131]
 [ 2.25970057  1.47742133  2.8737908   1.46905223  0.60520858]
 [ 5.48792643  0.88610202  5.7042413   0.61106901  7.98335976]
 [ 1.9672775   1.83536775  3.9057081   3.49361216  0.97024013]
 [ 0.63840524  0.55569299  2.30567889  2.96787756 12.92239711]
 [ 0.10016212  0.69199991  1.19153285  4.55665662  1.0830834 ]
 [15.85109567  0.41484041  9.51812168  9.73736335  3.11917023]
 [ 1.08839201  0.25174172  0.43283007  0.25219793  3.78221591]
 [ 0.3591443

d) You don’t worry too much about what this code is doing at this stage of the course, but for completeness: it imports the NumPy random number generation library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend data set of 50 independent and identically-distributed vectors from a log-normal
distribution.

In [37]:
# Create a fake dataset with 50 examples and 5 dimensions
data = np.exp(npr.randn(50, 5))

# Print the resulting dataset
print("Fake Dataset (50 examples, 5 dimensions):\n", data)


Fake Dataset (50 examples, 5 dimensions):
 [[1.37791347 1.11928551 1.70827099 1.84230911 0.97080212]
 [3.87318661 0.36736939 0.37406758 1.51646456 2.40941487]
 [0.98295489 3.31294774 0.45293917 0.27795471 5.05265654]
 [0.72408901 1.02920001 0.70575532 0.64325943 1.78059706]
 [1.41242175 0.69924941 0.47392408 1.34967751 1.54892389]
 [0.35261856 0.98462564 0.14545478 2.90765335 0.66783685]
 [1.02118451 0.53968331 1.59223661 0.13604646 0.2580403 ]
 [2.27263228 0.2134767  0.61701274 0.26998306 0.22220946]
 [0.33179984 1.26300036 0.80935992 0.21615501 1.5526403 ]
 [3.25721054 0.63379018 1.87814578 0.69220894 0.31825685]
 [0.23404073 1.32229755 0.21186    1.76644201 0.84522463]
 [1.25119407 2.4906339  2.16641622 1.54399797 0.41888959]
 [2.77487608 0.45153234 0.5087221  3.26458038 5.53440391]
 [1.71420116 0.38788104 1.5605881  0.87039243 1.14537667]
 [0.25662218 2.81201092 0.7701741  0.47980199 1.06256786]
 [0.6742078  0.36125268 1.13407856 1.15028521 7.82474731]
 [0.61096507 2.31358956 4.753

e) Now, compute the mean and standard deviation of each column. This should
result in two vectors of length 5. You’ll need to think a little bit about how to use
the axis argument to mean and std. Store these vectors into variables and print
both of them.

In [38]:
# Create a fake dataset with 50 examples and 5 dimensions
data = np.exp(npr.randn(50, 5))

# Compute the mean of each column (axis=0)
column_means = np.mean(data, axis=0)

# Compute the standard deviation of each column (axis=0)
column_std = np.std(data, axis=0)

# Print the resulting mean and standard deviation vectors
print("Mean of each column:\n", column_means)
print("Standard deviation of each column:\n", column_std)


Mean of each column:
 [1.62268955 1.58087729 1.44890925 1.52643766 1.5223247 ]
Standard deviation of each column:
 [1.58004182 1.57768148 1.45774755 1.50227961 1.82817081]


f) Now standardize the data matrix by 1) subtracting the mean off of each column,
and 2) dividing each column by its standard deviation. Do this via broadcasting,
and store the result in a matrix called normalized. To verify that you successfully
did it, compute the mean and standard deviation of
the columns of normalized and print them out.

In [39]:
# Create a fake dataset with 50 examples and 5 dimensions
data = np.exp(npr.randn(50, 5))

# Compute the mean and standard deviation of each column
column_means = np.mean(data, axis=0)
column_std = np.std(data, axis=0)

# Standardize the data
normalized = (data - column_means) / column_std

# Verify the standardization by computing the mean and standard deviation of the normalized data
normalized_means = np.mean(normalized, axis=0)
normalized_std = np.std(normalized, axis=0)

# Print the normalized data, mean, and standard deviation
print("Normalized Data:\n", normalized)
print("Mean of each column in normalized data:\n", normalized_means)
print("Standard deviation of each column in normalized data:\n", normalized_std)


Normalized Data:
 [[-5.95630349e-02  1.50493732e+00 -9.74114673e-01 -4.35787215e-01
   3.86015720e-03]
 [-3.91577502e-01 -2.31927223e-01  2.02908451e+00  3.34830112e-01
   1.05882404e+00]
 [-1.28855588e-01 -6.28931471e-01 -7.64859436e-01 -2.29175801e-01
  -7.56137731e-01]
 [ 3.42061481e-01 -5.53989483e-01 -5.93459836e-01  2.54972345e-01
  -5.76967915e-01]
 [-3.05378569e-01 -6.76335066e-01 -5.96284765e-01 -7.34564297e-01
   1.98249261e-01]
 [-5.70967481e-01  7.47243213e-01  8.85894322e-01 -1.55099313e-03
   5.48642845e-01]
 [-5.01612087e-01 -5.91277650e-01 -1.37419881e-01  1.77865009e+00
  -6.26662643e-01]
 [-4.18359447e-01 -3.77065174e-01 -8.63044278e-01  8.47913656e-01
   2.90996518e-01]
 [ 6.41503671e-01 -5.81890845e-01 -8.67764784e-01  1.08019189e+00
   6.43239365e-01]
 [-4.43250948e-01 -3.15274990e-01  1.50041786e-01 -6.57444433e-01
  -2.44604295e-01]
 [ 4.71211476e-02  8.49629930e-01  9.58878351e-01  1.86002144e+00
  -3.88803006e-01]
 [-2.87484262e-01 -3.88285945e-01 -8.08068859e-

# Q3.
a) A Vandermonde matrix is a matrix generated from a vector in which each column
of the matrix is an integer power starting from zero. So, if I have a column vector
[x1, x2, . . . , xN]^T,then the associated (square) Vandermonde matrix would be Use what you learned about broadcasting in the previous problem to write a
function that will produce a Vandermonde matrix for a vector [1, 2, . . . ,N]^T
for any N. Do it without using a loop. Here’s a stub to get you started:
def vandermonde (N):
vec = np.arange (N) +1
Use your function for N = 12, store it in variable named vander, and print the result.

In [40]:
def vandermonde(N):
 vec = np.arange(N) + 1
 return vec[:, np.newaxis] ** (vec - 1)

res = vandermonde(12)
print(res)


[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543     57

b) Now, let’s make a pretend linear system problem with this matrix. Create a vector
of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of
vander with the vector you just created and store that in a new vector and call it b.
Print the vector b.

In [41]:
# Assuming `vander` is a 12 x 12 matrix (as described previously)
# Create the Vandermonde matrix for demonstration (if not already defined)
vander = np.vander(np.arange(1, 13), increasing=True)  # 12x12 matrix with increasing order

# Create a vector of all ones of length 12
x = np.ones(12)

# Perform matrix-vector multiplication: b = vander * x
b = np.dot(vander, x)

# Print the resulting vector b
print("Vector b (result of matrix-vector multiplication):\n", b)


Vector b (result of matrix-vector multiplication):
 [1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 1.22713351e+09
 9.43953692e+08 3.73692871e+09 3.10225064e+08 3.10073456e+09]


c) First, solve the linear system the naïve way, pretending like you don’t know x.
Import numpy.linalg, invert V and multiply it by b. Print out your result. What
should you get for your answer? If the answer is different than what you
expected, write a sentence about that difference.

In [42]:
# Assuming `vander` is the same 12x12 matrix used previously
vander = np.vander(np.arange(1, 13), increasing=True)

# Create a vector of all ones for x (length 12)
x = np.ones(12)

# Compute b using matrix-vector multiplication
b = np.dot(vander, x)

# Import the linalg module to compute the inverse
import numpy.linalg as la

# Compute the inverse of `vander`
vander_inv = la.inv(vander)

# Solve for x using matrix multiplication: x = V^(-1) * b
x_solution = np.dot(vander_inv, b)

# Print the resulting vector x
print("Computed x using matrix inversion:\n", x_solution)

# Expected result
print("Expected x (all ones):\n", x)


Computed x using matrix inversion:
 [0.99888229 1.00003433 1.00135422 0.99969292 1.00003338 0.99999869
 0.99999999 1.         1.         1.         1.         1.        ]
Expected x (all ones):
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


d) Now, solve the same linear system using solve. Print out the result. Does it seem
more or less in line with what you’d expect?

In [43]:
# Assuming `vander` is the same 12x12 matrix used previously
vander = np.vander(np.arange(1, 13), increasing=True)

# Create a vector of all ones for x (length 12)
x = np.ones(12)

# Compute b using matrix-vector multiplication
b = np.dot(vander, x)

# Solve the linear system using np.linalg.solve
x_solved = la.solve(vander, b)

# Print the resulting vector x_solved
print("Solution using np.linalg.solve:\n", x_solved)

# Expected result
print("Expected x (all ones):\n", x)


Solution using np.linalg.solve:
 [0.99998821 1.00003034 0.99996973 1.00001556 0.99999545 1.00000078
 0.99999992 1.         1.         1.         1.         1.        ]
Expected x (all ones):
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


https://github.com/dishang8/Dishang_Dalwadi_24_27_12